# NIE DZIAŁA
version: '3.8'

services:
  app:
    build: .
    container_name: my-fullstack-app-container
    volumes:
      - .:/app
    working_dir: /app
    # command: ["gradle run"]
    command: ["gradle","run"]
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      - SDKMAN_DIR=/root/.sdkman
      - PATH=/root/.sdkman/bin:/root/.sdkman/candidates/kotlin/current/bin:/root/.sdkman/candidates/gradle/current/bin:$PATH
